---
converters:
    # Needed to convert to TTF and SVG
    # http://fontforge.github.io/
    ttf:
        path: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
        class: WebfontGenerator\Converters\TrueTypeConverter
    svg:
        path: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
        class: WebfontGenerator\Converters\ScalableVectorGraphicsConverter
    woff:
        # http://people.mozilla.com/~jkew/woff/
        path: /usr/bin/sfnt2woff
        class: WebfontGenerator\Converters\WoffConverter
    woff2:
        # https://github.com/google/woff2
        path: /usr/bin/woff2_compress
        class: WebfontGenerator\Converters\Woff2Converter
    eot:
        # http://code.google.com/p/ttf2eot/
        path: /usr/bin/ttf2eot
        class: WebfontGenerator\Converters\EmbedOpenTypeConverter
