converters:
    ttf:
        path: /usr/bin/fontforge
        class: WebfontGenerator\Converters\TrueTypeConverter
    sfd:
        path: /usr/bin/fontforge
        class: WebfontGenerator\Converters\SplitFontDBConverter
    afm:
        path: /usr/bin/fontforge
        class: WebfontGenerator\Converters\FontMetricsConverter
    svg:
        path: /usr/bin/fontforge
        class: WebfontGenerator\Converters\ScalableVectorGraphicsConverter
    woff:
        path: /usr/bin/sfnt2woff
        class: WebfontGenerator\Converters\WoffConverter
    woff2:
        path: /usr/bin/woff2_compress
        class: WebfontGenerator\Converters\Woff2Converter
    eot:
        path: /usr/bin/ttf2eot
        class: WebfontGenerator\Converters\EmbedOpenTypeConverter

pyftsubset: /usr/local/bin/pyftsubset